title: Co-Op Docs
theme: just-the-docs
baseurl: "/coop-docs" # Important for GitHub Pages
url: "https://coop-world.github.io"

color_scheme: light
search_enabled: true
nav_sort: case_insensitive

aux_links:
  GitHub: https://github.com/coop-world/coop-docs
